micronaut:
  application:
    name: stripe
  server:
    http-to-https-redirect: true
    cors:
      enabled: true
      configurations:
        web:
          allowed-origins: "*"
          allowed-methods: "POST,OPTIONS"
          allowed-headers: "*"
          exposed-headers: "*"
  security:
    enabled: true
    redirect:
      enabled: false
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
netty:
  default:
    allocator:
      max-order: 3
